loginsets:
  slinky:
    enabled: false

controller:
  extraConfMap:
    MCSPlugin: mcs/label
    MCSParameters: ondemand,ondemandselect
  service:
    spec:
      type: ClusterIP

nodesets:
  slinky:
    replicas: 0
